[build-system]
build-backend = 'mesonpy'
# Minimum requirements for the build system to execute.
requires = [
    'meson-python',
    'sagemath-standard >= 10.4',
    'cython >=3.0, != 3.0.3',
    'cysignals >=1.10.2',
]

[project]
name = "sagemath-bliss"
description = "SageMath: Graph (iso/auto)morphisms with bliss"
dependencies = [
    'cysignals >=1.10.2',
    'sagemath-standard >= 10.4',
]
dynamic = ["version"]
license = {text = "GNU General Public License (GPL) v2 or later"}
authors = [{name = "The Sage Developers", email = "sage-support@googlegroups.com"}]
classifiers = [
    "Development Status :: 6 - Mature",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
    "Operating System :: POSIX",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Mathematics",
]
requires-python = ">=3.9, <3.13"

[project.urls]
download = "https://doc.sagemath.org/html/en/installation/index.html"
"release notes" = "https://github.com/sagemath/sage/releases"
source = "https://github.com/sagemath/sage"
documentation = "https://doc.sagemath.org"
homepage = "https://www.sagemath.org"
tracker = "https://github.com/sagemath/sage/issues"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"
