# https://docs.astral.sh/ruff/configuration/#config-file-discovery

# Python 3.11 is the minimum supported version
target-version = "py311"

lint.select = [
    "E", # pycodestyle errors - https://docs.astral.sh/ruff/rules/#error-e
    "F", # pyflakes - https://docs.astral.sh/ruff/rules/#pyflakes-f
    "I", # isort - https://docs.astral.sh/ruff/rules/#isort-i
    "PL", # pylint - https://docs.astral.sh/ruff/rules/#pylint-pl
]
lint.ignore = [
    "E501", # Line too long - hard to avoid in doctests, and better handled by black.
]
