name: Trigger Changelog Generation

on:
  release:
    types: [published]

jobs:
  trigger-website-repo-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in website repo
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TRIGGER_SECRET: ${{ secrets.CHANGELOG_TRIGGER_SECRET }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/sagemath/website/actions/workflows/generate_changelog.yml/dispatches \
            -d '{"ref":"master","inputs":{"release_tag":"'"$RELEASE_TAG"'","trigger_secret":"'"$TRIGGER_SECRET"'"}}'
