# Configuration for GitHub Action running ruff
extend = "../../pyproject.toml"  # Start with the project configuration

[lint]
# Remove rules that we do not yet follow across the whole codebase.
ignore = [
  "E402", "E721", "E731", "E741", "E742", "E743",
  "F401", "F402", "F403", "F405", "F821", "F841",
  "I001",
  "PLC0206", "PLC0208", "PLC1802", "PLC2401", "PLC3002", "PLC0415",
  "PLE0302",
  "PLR0124", "PLR0402", "PLR0911", "PLR0912", "PLR0913", "PLR0915", "PLR1704", "PLR1711", "PLR1714", "PLR1716", "PLR1733", "PLR1736", "PLR2004", "PLR5501",
  "PLW0120", "PLW0211", "PLW0602", "PLW0603", "PLW0642", "PLW1508", "PLW1510", "PLW1641", "PLW2901", "PLW3301",
]
