# Configuration for GitHub Action running ruff
extend = "../../pyproject.toml"  # Start with the project configuration

[lint]
# Remove rules that we do not yet follow across the whole codebase.
# Roughly sorted by how easy these should be to fix.
extend-ignore = [
  "E742",    # 2 failures
  "PLW3301", # 3 failures, should be easy to autofix
  "PLW1510", # 18 failures, should be easy to autofix 
  "PLR1733", # 1 failure, should be easy to autofix
  "PLC3002", # 3 failures
  "PLE0302", # 3 failures
  "E721",    # 5 failures
  "PLR0124", # 7 failures
  "PLW1508", # 8 failures
  "PLR0402", # 90 failures, should be easy to autofix
  "PLR5501", # 375 failures, should be easy to autofix
  "PLC0206", # 39
  "PLW0602", # 43 failures
  "PLR1704", # 56 failures
  "PLW0642", # 61 failures
  "F841",    # 61 failures
  "PLW0603", # 94 failures
  "F403",    # 142 failures
  "F405",    # 163 failures
  "E731",    # 370 failures
  "PLW0211", # 495 failures
  "PLW2901", # 474 failures
  "F821",    # 2271 failures
  "F401",  # 583 failures
  "I001", # 2888 failures

  # The remaining failing rules were in ruff preview mode only when added to this file
  "E231",    # missing-whitespace
  "E226",    # missing-whitespace-around-arithmetic-operator
  "PLW3201", # bad-dunder-method-name
  "PLR6301", # no-self-use
  "E241",    # multiple-spaces-after-comma
  "E203",    # whitespace-before-punctuation
  "E265",    # no-space-after-block-comment
  "E201",    # whitespace-after-open-bracket
  "E261",    # too-few-spaces-before-inline-comment
  "PLR6104", # non-augmented-assignment
  "E202",    # whitespace-before-close-bracket
  "PLR6201", # literal-membership
  "E266",    # multiple-leading-hashes-for-block-comment
  "PLR1702", # too-many-nested-blocks
  "E262",    # no-space-after-inline-comment
  "PLW1514", # unspecified-encoding
  "PLC1901", # compare-to-empty-string
  "PLC2801", # unnecessary-dunder-call
  "E116",    # unexpected-indentation-comment
  "E114",    # indentation-with-invalid-multiple-comment
  "PLW0108", # unnecessary-lambda
  "PLC2701", # import-private-name
  "PLE4703", # modified-iterating-set
  ]
